// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GitShow")>]
[<assembly: AssemblyProductAttribute("GitShow")>]
[<assembly: AssemblyDescriptionAttribute("Code presentations with git")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GitShow"
    let [<Literal>] AssemblyProduct = "GitShow"
    let [<Literal>] AssemblyDescription = "Code presentations with git"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
